project:
  type: website
execute:
  freeze: auto
website:
  open-graph:
    locale: es_ES
    site-name: ainsuasty
  title: AInsuasty
  image: image/Insu.png
  favicon: image/favicon-32x32.png
  site-url: ainsuasty.com
  google-analytics: "UA-176122758-1" 
  repo-url: https://github.com/ainsu23/ainsuasty.git
  navbar:
    left: 
      - href: rworld.qmd
        text: "{{< fa flask >}} My data Lab"
      - href: more.qmd
        text: "{{< fa paper-plane >}} And more"
    right: 
      - href: books.qmd
        text: "{{< fa book >}} Recommended Books"
      - href: cv.html
        text: "{{< fa id-card >}} Vitae"
format:
  html:
   theme:
      light: flatly
      dark: darkly
